1.Застосування марківських моделей в задачах моделювання природних мов.

Можемо змоделювати речення у вигляді P(x_1...x_t) = p(x1)*p(x2|x1)*p(x3|x1, x2)* ... *p(xt|x1 ... xt-1). 
Нам потрібно знайти найбільш ймовірну послідовність тегів за даного речення. 
у = argmax P(y|x) = argmax p(x, y)
де P(x, y) = P(x|y)P(y) = Product from t=1 to T P(x_t|y_t)P(y_t|y_t-1) за умови Марківського припущення p(y) = product from t=1 to T P(y_t|y_t-1)


In [31]:
import numpy as np
from scipy.stats import multivariate_normal, norm
x1 = np.array([[1, 3], 
               [2, 4], 
               [3, 5]]
             )

x2 = np.array([[2, 5], 
               [0, 8], 
               [4, 1],
               [1, 1]]
             )
x3 = np.array([[1, 1], 
               [-5 , 4], 
               [0, 8]]
             )

x_new = np.array([2, 7])

In [32]:
mean_1 = np.mean(x1, axis=0)
mean_2 = np.mean(x1, axis=0)
mean_3 = np.mean(x3, axis=0)

In [35]:
cov_1 = np.cov(x1.T)
cov_2 = np.cov(x2.T)
cov_3 = np.cov(x3.T)

In [36]:
mean_1, cov_1

(array([2., 4.]), array([[1., 1.],
        [1., 1.]]))

In [37]:
mean_2, cov_2

(array([2., 4.]), array([[ 2.91666667, -3.75      ],
        [-3.75      , 11.58333333]]))

In [38]:
mean_3, cov_3

(array([-1.33333333,  4.33333333]), array([[10.33333333, -0.83333333],
        [-0.83333333, 12.33333333]]))

Не встигаю доробити, схоже що елемент x_new належить до 1-го класу

In [40]:
multivariate_normal(mean=mean_1, cov=cov_1).pdf(x_new)

LinAlgError: singular matrix

In [25]:
multivariate_normal(mean=mean_2, cov=cov_2).pdf(x_new)

0.018421385387315078

In [26]:
multivariate_normal(mean=mean_3, cov=cov_3).pdf(x_new)

0.005811745769734632