# Gaussian elemination method

In [28]:
import numpy as np
A = np.array([[1, 2, 3], [3, 5, 7], [1, 3, 4]], dtype='float')
b = np.array([3, 0, 1])
Ab = np.hstack([A, b.reshape(-1, 1)])
print(Ab)
print('=='*10)
n = len(b)
for i in range(n):
    a = Ab[i]
    for j in range(i + 1, n):
        b = Ab[j]
        m = a[i] / b[i]
        Ab[j] = a - m * b
        print(Ab)
        print('=='*10)
print("++"*20)
for i in range(n - 1, -1, -1):
    Ab[i] = Ab[i] / Ab[i, i]
    a = Ab[i]
    for j in range(i - 1, -1, -1):
        b = Ab[j]
        m = a[i] / b[i]
        Ab[j] = a - m * b
        print(Ab)
        print('=='*10)

x = Ab[:, 3]
print(x)

[[1. 2. 3. 3.]
 [3. 5. 7. 0.]
 [1. 3. 4. 1.]]
[[1.         2.         3.         3.        ]
 [0.         0.33333333 0.66666667 3.        ]
 [1.         3.         4.         1.        ]]
[[ 1.          2.          3.          3.        ]
 [ 0.          0.33333333  0.66666667  3.        ]
 [ 0.         -1.         -1.          2.        ]]
[[1.         2.         3.         3.        ]
 [0.         0.33333333 0.66666667 3.        ]
 [0.         0.         0.33333333 3.66666667]]
++++++++++++++++++++++++++++++++++++++++
[[ 1.   2.   3.   3. ]
 [ 0.  -0.5  0.   6.5]
 [ 0.   0.   1.  11. ]]
[[-0.33333333 -0.66666667  0.         10.        ]
 [ 0.         -0.5         0.          6.5       ]
 [ 0.          0.          1.         11.        ]]
[[ -0.5   0.    0.    2. ]
 [ -0.    1.   -0.  -13. ]
 [  0.    0.    1.   11. ]]
[ -4. -13.  11.]
